/** @fileoverview Terms of Service page with structured legal sections. */

import type { Metadata } from 'next'
import Link from 'next/link'
import { BRAND, PRICING, STATS } from '@/lib/constants'

export const metadata: Metadata = {
	title: 'Terms of Service',
}

const SECTIONS = [
	{
		id: 'acceptance',
		title: '1. Acceptance of Terms',
		content: `By accessing or using ${BRAND.name}, you agree to be bound by these Terms of Service. You must be at least 16 years old to use the service.`,
	},
	{
		id: 'description',
		title: '2. Description of Service',
		content: `${BRAND.name} is an AI-powered sales coaching platform available as a mobile application on iOS and Android. Features include AI roleplay practice, call recording and scoring, feedback and coaching, skill tracking, and team management tools.`,
	},
	{
		id: 'account',
		title: '3. Account Registration',
		content: `You must provide accurate information when creating an account. Each person may maintain one account. You are responsible for maintaining the security of your account credentials. ${BRAND.name} reserves the right to terminate accounts that violate these terms.`,
	},
	{
		id: 'billing',
		title: '4. Subscription and Billing',
		content: `Sales Rep plan: $${PRICING.individual.monthly}/mo or $${PRICING.individual.yearly}/yr. Teams plan: $${PRICING.teams.monthly}/mo per user with ${PRICING.teams.annualDiscount * 100}% off annual billing. A free ${STATS.trialDays}-day trial is available for the Sales Rep plan with full access and no credit card required. Subscriptions auto-renew unless cancelled before the renewal date. You may cancel anytime with no cancellation fees. Monthly billing stops at the end of the current period. Refunds are subject to Apple App Store and Google Play refund policies. Existing subscribers will receive 30 days notice of any price changes.`,
	},
	{
		id: 'acceptable-use',
		title: '5. Acceptable Use',
		content: `You may not use ${BRAND.name} for illegal activity, harassment, abuse, or harmful content in roleplay sessions. Reverse engineering, scraping, sharing account credentials, and commercial redistribution of ${BRAND.name} content or AI outputs are prohibited.`,
	},
	{
		id: 'recording-consent',
		title: '6. Call Recording Consent',
		content: `If you use the Ridealong recording feature, you are responsible for complying with applicable recording consent laws in your jurisdiction, including one-party and two-party consent requirements. ${BRAND.name} provides the recording tool but does not determine the legality of specific recordings. You must obtain consent from all parties as required by your jurisdiction. See our Privacy Policy at /privacy for details on how recording data is handled.`,
	},
	{
		id: 'ai-content',
		title: '7. AI-Generated Content',
		content: `AI coaching feedback, scores, and roleplay scenarios are generated by artificial intelligence. AI outputs are not a substitute for professional training, legal advice, or employment guidance. ${BRAND.name} does not guarantee specific sales performance outcomes. You retain ownership of your call recordings and data inputs.`,
	},
	{
		id: 'ip',
		title: '8. Intellectual Property',
		content: `${BRAND.name} retains intellectual property rights to the platform, AI models, and generated content. You retain ownership of content you upload, including scripts, product descriptions, and call recordings. A limited license is granted for personal and business use of AI-generated coaching content.`,
	},
	{
		id: 'data-privacy',
		title: '9. Data and Privacy',
		content: `Your data is encrypted in transit and at rest. We do not sell user data. We do not use your data to train AI models for other customers. You can delete your data at any time. See our full Privacy Policy at /privacy.`,
	},
	{
		id: 'liability',
		title: '10. Limitation of Liability',
		content: `${BRAND.name} is not responsible for sales performance outcomes, legal compliance of call recordings in your jurisdiction, or third-party service outages including Apple App Store, Google Play, and payment processor disruptions.`,
	},
	{
		id: 'indemnification',
		title: '11. Indemnification',
		content: `You agree to indemnify ${BRAND.name} against claims arising from your violation of these terms or applicable laws, including recording consent requirements.`,
	},
	{
		id: 'disputes',
		title: '12. Dispute Resolution',
		content: `These terms are governed by the laws of the State of Georgia, USA. Any disputes will be resolved through binding arbitration. You waive the right to participate in class action lawsuits.`,
	},
	{
		id: 'modifications',
		title: '13. Modifications to Terms',
		content: `We reserve the right to modify these terms. Material changes will be communicated with 30 days notice. Continued use of the service after changes take effect constitutes acceptance of the revised terms.`,
	},
	{
		id: 'termination',
		title: '14. Termination',
		content: `Either party may terminate the agreement at any time. Upon termination, your data will be retained for a reasonable period to allow for export, after which it will be deleted in accordance with our Privacy Policy.`,
	},
	{
		id: 'contact',
		title: '15. Contact',
		content: `If you have questions about these Terms of Service, contact us at hello@closercoach.ai or through the live chat widget on any page.`,
	},
] as const

export default function TermsPage() {
	return (
		<div className="bg-cc-foundation">
			<div className="mx-auto max-w-3xl px-6 py-24 md:py-32">
				<h1 className="display-lg text-white">Terms of Service</h1>
				<p className="mt-3 text-sm text-cc-text-muted">
					Last updated: April 2026
				</p>

				<div className="mt-12 space-y-10">
					{SECTIONS.map((section) => (
						<section key={section.id} id={section.id}>
							<h2 className="display-sm text-white">{section.title}</h2>
							<p className="mt-3 text-sm leading-relaxed text-cc-text-secondary">
								{section.content}
							</p>
						</section>
					))}
				</div>

				<div className="mt-16 text-center">
					<Link
						href="/"
						className="text-sm text-cc-text-secondary transition-colors hover:text-white"
					>
						&larr; Back to homepage
					</Link>
				</div>
			</div>
		</div>
	)
}
